initialdir = /home/zhangy/training-dynamics/emergent-misalignment/open_models

executable = /bin/bash

arguments = run_training.sh --config_path $(train_config) --merge_before_push false --push_to_private false --push_checkpoints_to_hub false

error = ./.yz_runs/$Fn(train_config).err
output = ./.yz_runs/$Fn(train_config).out
log = ./.yz_runs/$Fn(train_config).log

request_cpus = 4
request_memory = 96GB
request_gpus = 2
requirements = TARGET.CUDADeviceName == "NVIDIA H100 80GB HBM3"

# model output name should be the same with the train config file name
queue train_config matching files ./configs/generated_configs_loss/*finance-good*all*1e-05.json 
# ./configs/generated_configs_cycliclr/*32B*finance*all*7e-05*.json
# ./configs/generated_configs_schedule/*32B*finance*all*.json



